import { listingImage, partImages } from "@/lib/images";

export type CsyProduct = {
  slug: string;
  name: string;
  brand: string;
  image: string;
  mainCategory: string;
  mainLabel: string;
  subCategory: string;
  subLabel: string;
  price: number;
  description: string;
  badge?: string;
  discount?: string;
};

/** CSY Marine vitrin ürünleri — fiyatlar site içeriğine göre (TL) */
export const csyProducts: CsyProduct[] = [
  {
    slug: "akba-h220-tuvalet-kimyasal-3l",
    brand: "AKBA Kimya",
    name: "AKBA Kimya H-220 Konsantre Portatif Tuvalet Kimyasalı (Mavi Su) 3L",
    image: listingImage(partImages.bakim),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "tuvalet-pis-su",
    subLabel: "Atık Su / Tuvalet",
    price: 988.2,
    description: "Ambalaj: 3 Litre — Parçalayıcı — Kirli atık su tankına uygulanır.",
    discount: "%10",
  },
  {
    slug: "akba-h220-tuvalet-kimyasal-1l",
    brand: "AKBA Kimya",
    name: "AKBA Kimya H-220 Konsantre Portatif Tuvalet Kimyasalı (Mavi Su) 1L",
    image: listingImage(partImages.bakim),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "tuvalet-pis-su",
    subLabel: "Atık Su / Tuvalet",
    price: 418.5,
    description: "Ambalaj: 1 Litre — Parçalayıcı — Kirli atık su tankına uygulanır.",
    discount: "%10",
  },
  {
    slug: "thetford-aqua-kem-075",
    brand: "Thetford",
    name: "Thetford Aqua Kem Konsantre Portatif Tuvalet Kirli Su Kimyasalı 0,75 Litre",
    image: listingImage(partImages.bakim),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "tuvalet-pis-su",
    subLabel: "Atık Su / Tuvalet",
    price: 1035.62,
    description: "Parçalayıcı — Kirli su tankına uygulanır.",
    discount: "%8",
  },
  {
    slug: "thetford-aqua-rinse-075",
    brand: "Thetford",
    name: "Thetford Aqua Rinse Konsantre Portatif Tuvalet Temiz Su Kimyasalı 0,75 Litre",
    image: listingImage(partImages.bakim),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "tuvalet-pis-su",
    subLabel: "Atık Su / Tuvalet",
    price: 1035.62,
    description: "Koku giderici — Temiz su tankına uygulanır.",
    discount: "%8",
  },
  {
    slug: "thetford-porta-potti-565p",
    brand: "Thetford",
    name: "Thetford Portatif Tuvalet PPE 565P 21 Litre",
    image: listingImage(partImages.bakim),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "tuvalet-pis-su",
    subLabel: "Atık Su / Tuvalet",
    price: 12945.78,
    description: "Atık tankı 21 L — Oturma yüksekliği 443 mm — Porta Potti Excellence.",
    discount: "%8",
  },
  {
    slug: "portatif-tuvalet-20l",
    brand: "Diğer",
    name: "Portatif Tuvalet 20 L",
    image: listingImage(partImages.bakim),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "tuvalet-pis-su",
    subLabel: "Atık Su / Tuvalet",
    price: 2667.6,
    description: "Üst tank 10 L temiz su · Alt tank 20 L pis su.",
    discount: "%5",
  },
  {
    slug: "sikaflex-221-300ml",
    brand: "Sikaflex",
    name: "Sikaflex 221 Yapıştırıcı ve Sızdırmazlık 300ml Kartuş",
    image: listingImage(partImages.bakim),
    mainCategory: "boya-bakim",
    mainLabel: "Boya - Bakım",
    subCategory: "yapisitirici",
    subLabel: "Yapıştırıcılar ve Sızdırmazlık",
    price: 352.45,
    description: "Renk: Beyaz, Gri, Siyah — 300 ml kartuş.",
    discount: "%5",
  },
  {
    slug: "sikaflex-292i-300ml",
    brand: "Sikaflex",
    name: "Sikaflex 292i Marin Yapıştırıcı 300ml Kartuş",
    image: listingImage(partImages.bakim),
    mainCategory: "boya-bakim",
    mainLabel: "Boya - Bakım",
    subCategory: "yapisitirici",
    subLabel: "Yapıştırıcılar ve Sızdırmazlık",
    price: 922.2,
    description: "Marin yapıştırıcı — Beyaz — 300 ml.",
    discount: "%13",
  },
  {
    slug: "international-ultra-300-zehirli",
    brand: "International",
    name: "International Ultra 300 (EU) Zehirli Boya 2,5 Litre",
    image: listingImage(partImages.motor),
    mainCategory: "boya-bakim",
    mainLabel: "Boya - Bakım",
    subCategory: "zehirli-boya",
    subLabel: "Zehirli Boya",
    price: 9169,
    description: "Renk: Beyaz, Kırmızı, Lacivert, Mavi, Siyah — 2,5 L.",
    badge: "Çok satan",
  },
  {
    slug: "international-boatguard-750",
    brand: "International",
    name: "International Boatguard 100 Ekonomik Zehirli Boya 750Ml",
    image: listingImage(partImages.motor),
    mainCategory: "boya-bakim",
    mainLabel: "Boya - Bakım",
    subCategory: "zehirli-boya",
    subLabel: "Zehirli Boya",
    price: 1245.5,
    description: "Ekonomik zehirli boya — Kırmızı, Lacivert, Siyah.",
  },
  {
    slug: "international-danboline-sintine",
    brand: "International",
    name: "International Danboline Sintine Boyası 2,5 Litre",
    image: listingImage(partImages.motor),
    mainCategory: "boya-bakim",
    mainLabel: "Boya - Bakım",
    subCategory: "sintine-boyasi",
    subLabel: "Sintine Boyası",
    price: 4001.5,
    description: "Buz beyazı ve gri renk seçenekleri.",
  },
  {
    slug: "west-system-105-epoksi",
    brand: "West System",
    name: "West System 105 A Epoksi Reçine ve Sertleştirici 1,2 Kg",
    image: listingImage(partImages.bakim),
    mainCategory: "boya-bakim",
    mainLabel: "Boya - Bakım",
    subCategory: "epoksi",
    subLabel: "Epoksi",
    price: 3628.8,
    description: "Reçine 1 kg + sertleştirici 200 gr — 206 yavaş sertleştirici seçilebilir.",
  },
  {
    slug: "caulking-flex-polyolefin",
    brand: "Caulking Flex",
    name: "Caulking Flex Polyolefin 3'ü 1 Arada Yapıştırıcı 600ml Sosis",
    image: listingImage(partImages.bakim),
    mainCategory: "boya-bakim",
    mainLabel: "Boya - Bakım",
    subCategory: "yapisitirici",
    subLabel: "Yapıştırıcılar ve Sızdırmazlık",
    price: 960.36,
    description: "Elastik yapıştırma, sızdırmazlık ve derz dolgusu.",
  },
  {
    slug: "teak-wonder-koruyucu",
    brand: "Teak Wonder",
    name: "Teak Wonder Tik Koruyucu",
    image: listingImage(partImages.bakim),
    mainCategory: "boya-bakim",
    mainLabel: "Boya - Bakım",
    subCategory: "tik-bakim",
    subLabel: "Tik Temizlik ve Bakımı",
    price: 2517.5,
    description: "Tik yüzey temizlik ve koruma.",
    discount: "%5",
  },
  {
    slug: "ultra-underwater-led",
    brand: "ULTRA",
    name: "Ultra Underwater Su Altı LED Aydınlatma Lambası",
    image: listingImage(partImages.elektrik),
    mainCategory: "aydinlatma",
    mainLabel: "Aydınlatma",
    subCategory: "dis-aydinlatma",
    subLabel: "Dış Aydınlatma",
    price: 17000.28,
    description: "12V/24V — Beyaz veya mavi LED — 9000 lümen beyaz.",
    discount: "%1",
  },
  {
    slug: "seablaze-quattro-led",
    brand: "SeaBlaze",
    name: "SeaBlaze Quattro LED Sualtı Lambası",
    image: listingImage(partImages.elektrik),
    mainCategory: "aydinlatma",
    mainLabel: "Aydınlatma",
    subCategory: "dis-aydinlatma",
    subLabel: "Dış Aydınlatma",
    price: 28129.5,
    description: "Beyaz ve mavi LED sualtı aydınlatma.",
    discount: "%5",
  },
  {
    slug: "ultra-a1-usturmaca",
    brand: "ULTRA",
    name: "Ultra A1 Usturmaça 28×37 cm Beyaz",
    image: listingImage(partImages.pervane),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "usturmaça",
    subLabel: "Usturmaça ve Ekipmanı",
    price: 1208.4,
    description: "A1 serisi — 28×37 cm beyaz.",
  },
  {
    slug: "ultra-g1-usturmaca",
    brand: "ULTRA",
    name: "Ultra G1 Usturmaça 11×40 cm Beyaz",
    image: listingImage(partImages.pervane),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "usturmaça",
    subLabel: "Usturmaça ve Ekipmanı",
    price: 667.8,
    description: "G1 serisi — 11×40 cm beyaz.",
  },
  {
    slug: "ultra-f2-usturmaca",
    brand: "ULTRA",
    name: "Ultra F2 Usturmaça 20×60 cm Beyaz",
    image: listingImage(partImages.pervane),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "usturmaça",
    subLabel: "Usturmaça ve Ekipmanı",
    price: 2098.8,
    description: "F2 serisi — 20×60 cm beyaz.",
  },
  {
    slug: "can-ocak-evye-765",
    brand: "Can",
    name: "Can Kombinasyonlu Çift Gözlü Ocak & Evye Ayrık Cam",
    image: listingImage(partImages.bakim),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "mutfak",
    subLabel: "Mutfak Malzemeleri & Gereçleri",
    price: 20828.47,
    description: "765×355 mm — Sağ ocak sol evye — İtalya menşei.",
    discount: "%8",
  },
  {
    slug: "savoretti-dumen-simidi-35-30p",
    brand: "SAVORETTİ ARMANDO",
    name: "Savoretti Dümen Simidi 35 cm — Tipo 30P",
    image: listingImage(partImages.navigasyon),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "duzen-kumanda",
    subLabel: "Dümen - Kumanda",
    price: 13780,
    description: "Ø35 cm — Paslanmaz jant telleri — Deri kapak.",
  },
  {
    slug: "savoretti-dumen-simidi-28-9b",
    brand: "SAVORETTİ ARMANDO",
    name: "Savoretti Dümen Simidi 28 cm — Tipo 9B",
    image: listingImage(partImages.navigasyon),
    mainCategory: "tekne-malzemeleri",
    mainLabel: "Tekne Malzemeleri",
    subCategory: "duzen-kumanda",
    subLabel: "Dümen - Kumanda",
    price: 2809,
    description: "Ø28 cm — Paslanmaz çelik kapak.",
  },
  {
    slug: "ihoybox24-otopilot",
    brand: "IHOY CAPTAIN",
    name: "IHOYBOX24 Otopilot",
    image: listingImage(partImages.navigasyon),
    mainCategory: "elektronik",
    mainLabel: "Elektronik",
    subCategory: "oto-pilot",
    subLabel: "Oto Pilot",
    price: 126140,
    description: "12V DC — Konik dümen mili uyumlu — Maks. tork 6 Nm.",
    badge: "Profesyonel",
  },
  {
    slug: "denox-ocean3-hoparlor",
    brand: "Denox",
    name: "Denox Ocean 3 Marin Hoparlör — 40 Watt Çift",
    image: listingImage(partImages.elektrik),
    mainCategory: "elektronik",
    mainLabel: "Elektronik",
    subCategory: "marin-hoparlorler",
    subLabel: "Marin Hoparlörler",
    price: 3186,
    description: "8 ohm — 40-120 W — Marin kullanım.",
  },
];

export function formatPrice(tl: number) {
  return `${tl.toLocaleString("tr-TR", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} ₺`;
}

export function getCsyProduct(slug: string) {
  return csyProducts.find((p) => p.slug === slug);
}

export function filterCsyProducts(opts: { main?: string; sub?: string }) {
  return csyProducts.filter((p) => {
    if (opts.main && p.mainCategory !== opts.main) return false;
    if (opts.sub && p.subCategory !== opts.sub) return false;
    return true;
  });
}
